# Generated by Django 5.0.4 on 2024-04-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
