# Generated by Django 5.0.4 on 2024-05-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
